# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screens/board.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import settings
import serialConnector
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_boardPage(object):
    def setupUi(self, boardPage):
        boardPage.setObjectName("boardPage")
        boardPage.setEnabled(True)
        boardPage.resize(1200, 800)
        boardPage.setMinimumSize(QtCore.QSize(1200, 800))
        boardPage.setMaximumSize(QtCore.QSize(1200, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
            "..\images\icon\icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        boardPage.setWindowIcon(icon)
        boardPage.setStyleSheet("background-color: #fff8e1;")
        self.centralwidget = QtWidgets.QWidget(boardPage)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(510, 70, 561, 561))
        self.widget.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.widget.setObjectName("widget")
        self.a1 = QtWidgets.QPushButton(self.widget)
        self.a1.setGeometry(QtCore.QRect(0, 0, 70, 70))
        self.a1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.a1.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.a1.setText("")
        self.a1.setIconSize(QtCore.QSize(50, 50))
        self.a1.setObjectName("a1")
        self.b1 = QtWidgets.QPushButton(self.widget)
        self.b1.setGeometry(QtCore.QRect(70, 0, 70, 70))
        self.b1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b1.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.b1.setText("")
        self.b1.setIconSize(QtCore.QSize(50, 50))
        self.b1.setObjectName("b1")
        self.c1 = QtWidgets.QPushButton(self.widget)
        self.c1.setGeometry(QtCore.QRect(140, 0, 70, 70))
        self.c1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.c1.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.c1.setText("")
        self.c1.setIconSize(QtCore.QSize(50, 50))
        self.c1.setObjectName("c1")
        self.d1 = QtWidgets.QPushButton(self.widget)
        self.d1.setGeometry(QtCore.QRect(210, 0, 70, 70))
        self.d1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.d1.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.d1.setText("")
        self.d1.setIconSize(QtCore.QSize(50, 50))
        self.d1.setObjectName("d1")
        self.e1 = QtWidgets.QPushButton(self.widget)
        self.e1.setGeometry(QtCore.QRect(280, 0, 70, 70))
        self.e1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.e1.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.e1.setText("")
        self.e1.setIconSize(QtCore.QSize(50, 50))
        self.e1.setObjectName("e1")
        self.f1 = QtWidgets.QPushButton(self.widget)
        self.f1.setGeometry(QtCore.QRect(350, 0, 70, 70))
        self.f1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.f1.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.f1.setText("")
        self.f1.setIconSize(QtCore.QSize(50, 50))
        self.f1.setObjectName("f1")
        self.g1 = QtWidgets.QPushButton(self.widget)
        self.g1.setGeometry(QtCore.QRect(420, 0, 70, 70))
        self.g1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.g1.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.g1.setText("")
        self.g1.setIconSize(QtCore.QSize(50, 50))
        self.g1.setObjectName("g1")
        self.h1 = QtWidgets.QPushButton(self.widget)
        self.h1.setGeometry(QtCore.QRect(490, 0, 70, 70))
        self.h1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.h1.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.h1.setText("")
        self.h1.setIconSize(QtCore.QSize(50, 50))
        self.h1.setObjectName("h1")
        self.f2 = QtWidgets.QPushButton(self.widget)
        self.f2.setGeometry(QtCore.QRect(350, 70, 70, 70))
        self.f2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.f2.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.f2.setText("")
        self.f2.setIconSize(QtCore.QSize(50, 50))
        self.f2.setObjectName("f2")
        self.h2 = QtWidgets.QPushButton(self.widget)
        self.h2.setGeometry(QtCore.QRect(490, 70, 70, 70))
        self.h2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.h2.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.h2.setText("")
        self.h2.setIconSize(QtCore.QSize(50, 50))
        self.h2.setObjectName("h2")
        self.c2 = QtWidgets.QPushButton(self.widget)
        self.c2.setGeometry(QtCore.QRect(140, 70, 70, 70))
        self.c2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.c2.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.c2.setText("")
        self.c2.setIconSize(QtCore.QSize(50, 50))
        self.c2.setObjectName("c2")
        self.e2 = QtWidgets.QPushButton(self.widget)
        self.e2.setGeometry(QtCore.QRect(280, 70, 70, 70))
        self.e2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.e2.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.e2.setText("")
        self.e2.setIconSize(QtCore.QSize(50, 50))
        self.e2.setObjectName("e2")
        self.d2 = QtWidgets.QPushButton(self.widget)
        self.d2.setGeometry(QtCore.QRect(210, 70, 70, 70))
        self.d2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.d2.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.d2.setText("")
        self.d2.setIconSize(QtCore.QSize(50, 50))
        self.d2.setObjectName("d2")
        self.a2 = QtWidgets.QPushButton(self.widget)
        self.a2.setGeometry(QtCore.QRect(0, 70, 70, 70))
        self.a2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.a2.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.a2.setText("")
        self.a2.setIconSize(QtCore.QSize(50, 50))
        self.a2.setObjectName("a2")
        self.b2 = QtWidgets.QPushButton(self.widget)
        self.b2.setGeometry(QtCore.QRect(70, 70, 70, 70))
        self.b2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b2.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.b2.setText("")
        self.b2.setIconSize(QtCore.QSize(50, 50))
        self.b2.setObjectName("b2")
        self.g2 = QtWidgets.QPushButton(self.widget)
        self.g2.setGeometry(QtCore.QRect(420, 70, 70, 70))
        self.g2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.g2.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.g2.setText("")
        self.g2.setIconSize(QtCore.QSize(50, 50))
        self.g2.setObjectName("g2")
        self.f3 = QtWidgets.QPushButton(self.widget)
        self.f3.setGeometry(QtCore.QRect(350, 140, 70, 70))
        self.f3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.f3.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.f3.setText("")
        self.f3.setIconSize(QtCore.QSize(50, 50))
        self.f3.setObjectName("f3")
        self.h3 = QtWidgets.QPushButton(self.widget)
        self.h3.setGeometry(QtCore.QRect(490, 140, 70, 70))
        self.h3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.h3.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.h3.setText("")
        self.h3.setIconSize(QtCore.QSize(50, 50))
        self.h3.setObjectName("h3")
        self.c3 = QtWidgets.QPushButton(self.widget)
        self.c3.setGeometry(QtCore.QRect(140, 140, 70, 70))
        self.c3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.c3.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.c3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(
            "images\icon\white-disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.c3.setIcon(icon1)
        self.c3.setIconSize(QtCore.QSize(50, 50))
        self.c3.setObjectName("c3")
        self.e3 = QtWidgets.QPushButton(self.widget)
        self.e3.setGeometry(QtCore.QRect(280, 140, 70, 70))
        self.e3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.e3.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.e3.setText("")
        self.e3.setIconSize(QtCore.QSize(50, 50))
        self.e3.setObjectName("e3")
        self.d3 = QtWidgets.QPushButton(self.widget)
        self.d3.setGeometry(QtCore.QRect(210, 140, 70, 70))
        self.d3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.d3.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.d3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(
            "images\icon\black-disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.d3.setIcon(icon2)
        self.d3.setIconSize(QtCore.QSize(50, 50))
        self.d3.setObjectName("d3")
        self.a3 = QtWidgets.QPushButton(self.widget)
        self.a3.setGeometry(QtCore.QRect(0, 140, 70, 70))
        self.a3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.a3.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.a3.setText("")
        self.a3.setIconSize(QtCore.QSize(50, 50))
        self.a3.setObjectName("a3")
        self.b3 = QtWidgets.QPushButton(self.widget)
        self.b3.setGeometry(QtCore.QRect(70, 140, 70, 70))
        self.b3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b3.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.b3.setText("")
        self.b3.setIconSize(QtCore.QSize(50, 50))
        self.b3.setObjectName("b3")
        self.g3 = QtWidgets.QPushButton(self.widget)
        self.g3.setGeometry(QtCore.QRect(420, 140, 70, 70))
        self.g3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.g3.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.g3.setText("")
        self.g3.setIconSize(QtCore.QSize(50, 50))
        self.g3.setObjectName("g3")
        self.f4 = QtWidgets.QPushButton(self.widget)
        self.f4.setGeometry(QtCore.QRect(350, 210, 70, 70))
        self.f4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.f4.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.f4.setText("")
        self.f4.setIconSize(QtCore.QSize(50, 50))
        self.f4.setObjectName("f4")
        self.h4 = QtWidgets.QPushButton(self.widget)
        self.h4.setGeometry(QtCore.QRect(490, 210, 70, 70))
        self.h4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.h4.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.h4.setText("")
        self.h4.setIconSize(QtCore.QSize(50, 50))
        self.h4.setObjectName("h4")
        self.c4 = QtWidgets.QPushButton(self.widget)
        self.c4.setGeometry(QtCore.QRect(140, 210, 70, 70))
        self.c4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.c4.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.c4.setText("")
        self.c4.setIconSize(QtCore.QSize(50, 50))
        self.c4.setObjectName("c4")
        self.e4 = QtWidgets.QPushButton(self.widget)
        self.e4.setGeometry(QtCore.QRect(280, 210, 70, 70))
        self.e4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.e4.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.e4.setText("")
        self.e4.setIconSize(QtCore.QSize(50, 50))
        self.e4.setObjectName("e4")
        self.d4 = QtWidgets.QPushButton(self.widget)
        self.d4.setGeometry(QtCore.QRect(210, 210, 70, 70))
        self.d4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.d4.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.d4.setText("")
        self.d4.setIconSize(QtCore.QSize(50, 50))
        self.d4.setObjectName("d4")
        self.a4 = QtWidgets.QPushButton(self.widget)
        self.a4.setGeometry(QtCore.QRect(0, 210, 70, 70))
        self.a4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.a4.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.a4.setText("")
        self.a4.setIconSize(QtCore.QSize(50, 50))
        self.a4.setObjectName("a4")
        self.b4 = QtWidgets.QPushButton(self.widget)
        self.b4.setGeometry(QtCore.QRect(70, 210, 70, 70))
        self.b4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b4.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.b4.setText("")
        self.b4.setIconSize(QtCore.QSize(50, 50))
        self.b4.setObjectName("b4")
        self.g4 = QtWidgets.QPushButton(self.widget)
        self.g4.setGeometry(QtCore.QRect(420, 210, 70, 70))
        self.g4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.g4.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.g4.setText("")
        self.g4.setIconSize(QtCore.QSize(50, 50))
        self.g4.setObjectName("g4")
        self.f5 = QtWidgets.QPushButton(self.widget)
        self.f5.setGeometry(QtCore.QRect(350, 280, 70, 70))
        self.f5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.f5.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.f5.setText("")
        self.f5.setIconSize(QtCore.QSize(50, 50))
        self.f5.setObjectName("f5")
        self.h5 = QtWidgets.QPushButton(self.widget)
        self.h5.setGeometry(QtCore.QRect(490, 280, 70, 70))
        self.h5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.h5.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.h5.setText("")
        self.h5.setIconSize(QtCore.QSize(50, 50))
        self.h5.setObjectName("h5")
        self.c5 = QtWidgets.QPushButton(self.widget)
        self.c5.setGeometry(QtCore.QRect(140, 280, 70, 70))
        self.c5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.c5.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.c5.setText("")
        self.c5.setIconSize(QtCore.QSize(50, 50))
        self.c5.setObjectName("c5")
        self.e5 = QtWidgets.QPushButton(self.widget)
        self.e5.setGeometry(QtCore.QRect(280, 280, 70, 70))
        self.e5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.e5.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.e5.setText("")
        self.e5.setIconSize(QtCore.QSize(50, 50))
        self.e5.setObjectName("e5")
        self.d5 = QtWidgets.QPushButton(self.widget)
        self.d5.setGeometry(QtCore.QRect(210, 280, 70, 70))
        self.d5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.d5.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.d5.setText("")
        self.d5.setIconSize(QtCore.QSize(50, 50))
        self.d5.setObjectName("d5")
        self.a5 = QtWidgets.QPushButton(self.widget)
        self.a5.setGeometry(QtCore.QRect(0, 280, 70, 70))
        self.a5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.a5.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.a5.setText("")
        self.a5.setIconSize(QtCore.QSize(50, 50))
        self.a5.setObjectName("a5")
        self.b5 = QtWidgets.QPushButton(self.widget)
        self.b5.setGeometry(QtCore.QRect(70, 280, 70, 70))
        self.b5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b5.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.b5.setText("")
        self.b5.setIconSize(QtCore.QSize(50, 50))
        self.b5.setObjectName("b5")
        self.g5 = QtWidgets.QPushButton(self.widget)
        self.g5.setGeometry(QtCore.QRect(420, 280, 70, 70))
        self.g5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.g5.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.g5.setText("")
        self.g5.setIconSize(QtCore.QSize(50, 50))
        self.g5.setObjectName("g5")
        self.f6 = QtWidgets.QPushButton(self.widget)
        self.f6.setGeometry(QtCore.QRect(350, 350, 70, 70))
        self.f6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.f6.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.f6.setText("")
        self.f6.setIconSize(QtCore.QSize(50, 50))
        self.f6.setObjectName("f6")
        self.h6 = QtWidgets.QPushButton(self.widget)
        self.h6.setGeometry(QtCore.QRect(490, 350, 70, 70))
        self.h6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.h6.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.h6.setText("")
        self.h6.setIconSize(QtCore.QSize(50, 50))
        self.h6.setObjectName("h6")
        self.c6 = QtWidgets.QPushButton(self.widget)
        self.c6.setGeometry(QtCore.QRect(140, 350, 70, 70))
        self.c6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.c6.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.c6.setText("")
        self.c6.setIconSize(QtCore.QSize(50, 50))
        self.c6.setObjectName("c6")
        self.e6 = QtWidgets.QPushButton(self.widget)
        self.e6.setGeometry(QtCore.QRect(280, 350, 70, 70))
        self.e6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.e6.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.e6.setText("")
        self.e6.setIconSize(QtCore.QSize(50, 50))
        self.e6.setObjectName("e6")
        self.d6 = QtWidgets.QPushButton(self.widget)
        self.d6.setGeometry(QtCore.QRect(210, 350, 70, 70))
        self.d6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.d6.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.d6.setText("")
        self.d6.setIconSize(QtCore.QSize(50, 50))
        self.d6.setObjectName("d6")
        self.a6 = QtWidgets.QPushButton(self.widget)
        self.a6.setGeometry(QtCore.QRect(0, 350, 70, 70))
        self.a6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.a6.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.a6.setText("")
        self.a6.setIconSize(QtCore.QSize(50, 50))
        self.a6.setObjectName("a6")
        self.b6 = QtWidgets.QPushButton(self.widget)
        self.b6.setGeometry(QtCore.QRect(70, 350, 70, 70))
        self.b6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b6.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.b6.setText("")
        self.b6.setIconSize(QtCore.QSize(50, 50))
        self.b6.setObjectName("b6")
        self.g6 = QtWidgets.QPushButton(self.widget)
        self.g6.setGeometry(QtCore.QRect(420, 350, 70, 70))
        self.g6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.g6.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.g6.setText("")
        self.g6.setIconSize(QtCore.QSize(50, 50))
        self.g6.setObjectName("g6")
        self.f7 = QtWidgets.QPushButton(self.widget)
        self.f7.setGeometry(QtCore.QRect(350, 420, 70, 70))
        self.f7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.f7.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.f7.setText("")
        self.f7.setIconSize(QtCore.QSize(50, 50))
        self.f7.setObjectName("f7")
        self.h7 = QtWidgets.QPushButton(self.widget)
        self.h7.setGeometry(QtCore.QRect(490, 420, 70, 70))
        self.h7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.h7.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.h7.setText("")
        self.h7.setIconSize(QtCore.QSize(50, 50))
        self.h7.setObjectName("h7")
        self.c7 = QtWidgets.QPushButton(self.widget)
        self.c7.setGeometry(QtCore.QRect(140, 420, 70, 70))
        self.c7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.c7.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.c7.setText("")
        self.c7.setIconSize(QtCore.QSize(50, 50))
        self.c7.setObjectName("c7")
        self.e7 = QtWidgets.QPushButton(self.widget)
        self.e7.setGeometry(QtCore.QRect(280, 420, 70, 70))
        self.e7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.e7.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.e7.setText("")
        self.e7.setIconSize(QtCore.QSize(50, 50))
        self.e7.setObjectName("e7")
        self.d7 = QtWidgets.QPushButton(self.widget)
        self.d7.setGeometry(QtCore.QRect(210, 420, 70, 70))
        self.d7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.d7.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.d7.setText("")
        self.d7.setIconSize(QtCore.QSize(50, 50))
        self.d7.setObjectName("d7")
        self.a7 = QtWidgets.QPushButton(self.widget)
        self.a7.setGeometry(QtCore.QRect(0, 420, 70, 70))
        self.a7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.a7.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.a7.setText("")
        self.a7.setIconSize(QtCore.QSize(50, 50))
        self.a7.setObjectName("a7")
        self.b7 = QtWidgets.QPushButton(self.widget)
        self.b7.setGeometry(QtCore.QRect(70, 420, 70, 70))
        self.b7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b7.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.b7.setText("")
        self.b7.setIconSize(QtCore.QSize(50, 50))
        self.b7.setObjectName("b7")
        self.g7 = QtWidgets.QPushButton(self.widget)
        self.g7.setGeometry(QtCore.QRect(420, 420, 70, 70))
        self.g7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.g7.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.g7.setText("")
        self.g7.setIconSize(QtCore.QSize(50, 50))
        self.g7.setObjectName("g7")
        self.f8 = QtWidgets.QPushButton(self.widget)
        self.f8.setGeometry(QtCore.QRect(350, 490, 70, 70))
        self.f8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.f8.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.f8.setText("")
        self.f8.setIconSize(QtCore.QSize(50, 50))
        self.f8.setObjectName("f8")
        self.h8 = QtWidgets.QPushButton(self.widget)
        self.h8.setGeometry(QtCore.QRect(490, 490, 70, 70))
        self.h8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.h8.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.h8.setText("")
        self.h8.setIconSize(QtCore.QSize(50, 50))
        self.h8.setObjectName("h8")
        self.c8 = QtWidgets.QPushButton(self.widget)
        self.c8.setGeometry(QtCore.QRect(140, 490, 70, 70))
        self.c8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.c8.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.c8.setText("")
        self.c8.setIconSize(QtCore.QSize(50, 50))
        self.c8.setObjectName("c8")
        self.e8 = QtWidgets.QPushButton(self.widget)
        self.e8.setGeometry(QtCore.QRect(280, 490, 70, 70))
        self.e8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.e8.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.e8.setText("")
        self.e8.setIconSize(QtCore.QSize(50, 50))
        self.e8.setObjectName("e8")
        self.d8 = QtWidgets.QPushButton(self.widget)
        self.d8.setGeometry(QtCore.QRect(210, 490, 70, 70))
        self.d8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.d8.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.d8.setText("")
        self.d8.setIconSize(QtCore.QSize(50, 50))
        self.d8.setObjectName("d8")
        self.a8 = QtWidgets.QPushButton(self.widget)
        self.a8.setGeometry(QtCore.QRect(0, 490, 70, 70))
        self.a8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.a8.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.a8.setText("")
        self.a8.setIconSize(QtCore.QSize(50, 50))
        self.a8.setObjectName("a8")
        self.b8 = QtWidgets.QPushButton(self.widget)
        self.b8.setGeometry(QtCore.QRect(70, 490, 70, 70))
        self.b8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b8.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.b8.setText("")
        self.b8.setIconSize(QtCore.QSize(50, 50))
        self.b8.setObjectName("b8")
        self.g8 = QtWidgets.QPushButton(self.widget)
        self.g8.setGeometry(QtCore.QRect(420, 490, 70, 70))
        self.g8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.g8.setStyleSheet(
            "background-color: #43a047;\n"
            "border-radius: 0;\n"
            "border: 0.5px solid #757575;"
        )
        self.g8.setText("")
        self.g8.setIconSize(QtCore.QSize(50, 50))
        self.g8.setObjectName("g8")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(510, 630, 561, 31))
        self.frame.setStyleSheet(
            "background-color: #ffecb3;\n"
            "border: 0;\n"
        )
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 71, 31))
        self.label_9.setStyleSheet(
            "background: None;\n"
            "color: #5d4037;"
        )
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(70, 0, 71, 31))
        self.label_10.setStyleSheet(
            "background: None;\n"
            "color: #5d4037;"
        )
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(140, 0, 71, 31))
        self.label_11.setStyleSheet(
            "background: None;\n"
            "color: #5d4037;"
        )
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(280, 0, 71, 31))
        self.label_13.setStyleSheet(
            "background: None;\n"
            "color: #5d4037;"
        )
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(350, 0, 71, 31))
        self.label_14.setStyleSheet(
            "background: None;\n"
            "color: #5d4037;"
        )
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(420, 0, 71, 31))
        self.label_15.setStyleSheet(
            "background: None;\n"
            "color: #5d4037;"
        )
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(490, 0, 71, 31))
        self.label_16.setStyleSheet(
            "background: None;\n"
            "color: #5d4037;"
        )
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(1070, 70, 31, 591))
        self.frame_2.setStyleSheet(
            "background-color: #ffecb3;\n"
            "border: 0;\n"
        )
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(0, 15, 31, 41))
        self.label.setStyleSheet(
            "background: None;\n"
            "color: #5d4037;"
        )
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(0, 90, 31, 41))
        self.label_2.setStyleSheet(
            "background: None;\n"
            "color: #5d4037;"
        )
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(0, 160, 31, 41))
        self.label_3.setStyleSheet(
            "background: None;\n"
            "color: #5d4037;"
        )
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1070, 290, 31, 41))
        self.label_4.setStyleSheet(
            "background: None;\n"
            "color: #5d4037;"
        )
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1070, 360, 31, 41))
        self.label_5.setStyleSheet(
            "background: None;\n"
            "color: #5d4037;"
        )
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1070, 430, 31, 41))
        self.label_6.setStyleSheet(
            "background: None;\n"
            "color: #5d4037;"
        )
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1070, 500, 31, 41))
        self.label_7.setStyleSheet(
            "background: None;\n"
            "color: #5d4037;"
        )
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1070, 570, 31, 41))
        self.label_8.setStyleSheet(
            "background: None;\n"
            "color: #5d4037;"
        )
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(720, 630, 71, 31))
        self.label_12.setStyleSheet(
            "background: None;\n"
            "color: #5d4037;"
        )
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(70, 160, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(70, 70, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.blackScore = QtWidgets.QLabel(self.centralwidget)
        self.blackScore.setGeometry(QtCore.QRect(240, 60, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        self.blackScore.setFont(font)
        self.blackScore.setObjectName("blackScore")
        self.whiteScore = QtWidgets.QLabel(self.centralwidget)
        self.whiteScore.setGeometry(QtCore.QRect(240, 150, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        self.whiteScore.setFont(font)
        self.whiteScore.setObjectName("whiteScore")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(60, 350, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.currentMoveLabel = QtWidgets.QLabel(self.centralwidget)
        self.currentMoveLabel.setGeometry(QtCore.QRect(270, 350, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.currentMoveLabel.setFont(font)
        self.currentMoveLabel.setStyleSheet("color: #5c6bc0;")
        self.currentMoveLabel.setObjectName("currentMoveLabel")
        self.validMoveLabel = QtWidgets.QLabel(self.centralwidget)
        self.validMoveLabel.setGeometry(QtCore.QRect(40, 510, 391, 91))
        self.validMoveLabel.setText("")
        self.validMoveLabel.setObjectName("validMoveLabel")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.validMoveLabel.setFont(font)
        self.validMoveLabel.setStyleSheet("color: #5c6bc0;")
        self.validMoveLabel.setObjectName("validMoveLabel")
        boardPage.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(boardPage)
        self.statusbar.setObjectName("statusbar")
        boardPage.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(boardPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        boardPage.setMenuBar(self.menubar)

        self.retranslateUi(boardPage)
        QtCore.QMetaObject.connectSlotsByName(boardPage)

        self.a1.clicked.connect(lambda: self.boardButtonClicked(
            self.a1.objectName(), settings.PLAYER))
        self.a2.clicked.connect(lambda: self.boardButtonClicked(
            self.a2.objectName(), settings.PLAYER))
        self.a3.clicked.connect(lambda: self.boardButtonClicked(
            self.a3.objectName(), settings.PLAYER))
        self.a4.clicked.connect(lambda: self.boardButtonClicked(
            self.a4.objectName(), settings.PLAYER))
        self.a5.clicked.connect(lambda: self.boardButtonClicked(
            self.a5.objectName(), settings.PLAYER))
        self.a6.clicked.connect(lambda: self.boardButtonClicked(
            self.a6.objectName(), settings.PLAYER))
        self.a7.clicked.connect(lambda: self.boardButtonClicked(
            self.a7.objectName(), settings.PLAYER))
        self.a8.clicked.connect(lambda: self.boardButtonClicked(
            self.a8.objectName(), settings.PLAYER))

        self.b1.clicked.connect(lambda: self.boardButtonClicked(
            self.b1.objectName(), settings.PLAYER))
        self.b2.clicked.connect(lambda: self.boardButtonClicked(
            self.b2.objectName(), settings.PLAYER))
        self.b3.clicked.connect(lambda: self.boardButtonClicked(
            self.b3.objectName(), settings.PLAYER))
        self.b4.clicked.connect(lambda: self.boardButtonClicked(
            self.b4.objectName(), settings.PLAYER))
        self.b5.clicked.connect(lambda: self.boardButtonClicked(
            self.b5.objectName(), settings.PLAYER))
        self.b6.clicked.connect(lambda: self.boardButtonClicked(
            self.b6.objectName(), settings.PLAYER))
        self.b7.clicked.connect(lambda: self.boardButtonClicked(
            self.b7.objectName(), settings.PLAYER))
        self.b8.clicked.connect(lambda: self.boardButtonClicked(
            self.b8.objectName(), settings.PLAYER))

        self.c1.clicked.connect(lambda: self.boardButtonClicked(
            self.c1.objectName(), settings.PLAYER))
        self.c2.clicked.connect(lambda: self.boardButtonClicked(
            self.c2.objectName(), settings.PLAYER))
        self.c3.clicked.connect(lambda: self.boardButtonClicked(
            self.c3.objectName(), settings.PLAYER))
        self.c4.clicked.connect(lambda: self.boardButtonClicked(
            self.c4.objectName(), settings.PLAYER))
        self.c5.clicked.connect(lambda: self.boardButtonClicked(
            self.c5.objectName(), settings.PLAYER))
        self.c6.clicked.connect(lambda: self.boardButtonClicked(
            self.c6.objectName(), settings.PLAYER))
        self.c7.clicked.connect(lambda: self.boardButtonClicked(
            self.c7.objectName(), settings.PLAYER))
        self.c8.clicked.connect(lambda: self.boardButtonClicked(
            self.c8.objectName(), settings.PLAYER))

        self.d1.clicked.connect(lambda: self.boardButtonClicked(
            self.d1.objectName(), settings.PLAYER))
        self.d2.clicked.connect(lambda: self.boardButtonClicked(
            self.d2.objectName(), settings.PLAYER))
        self.d3.clicked.connect(lambda: self.boardButtonClicked(
            self.d3.objectName(), settings.PLAYER))
        self.d4.clicked.connect(lambda: self.boardButtonClicked(
            self.d4.objectName(), settings.PLAYER))
        self.d5.clicked.connect(lambda: self.boardButtonClicked(
            self.d5.objectName(), settings.PLAYER))
        self.d6.clicked.connect(lambda: self.boardButtonClicked(
            self.d6.objectName(), settings.PLAYER))
        self.d7.clicked.connect(lambda: self.boardButtonClicked(
            self.d7.objectName(), settings.PLAYER))
        self.d8.clicked.connect(lambda: self.boardButtonClicked(
            self.d8.objectName(), settings.PLAYER))

        self.e1.clicked.connect(lambda: self.boardButtonClicked(
            self.e1.objectName(), settings.PLAYER))
        self.e2.clicked.connect(lambda: self.boardButtonClicked(
            self.e2.objectName(), settings.PLAYER))
        self.e3.clicked.connect(lambda: self.boardButtonClicked(
            self.e3.objectName(), settings.PLAYER))
        self.e4.clicked.connect(lambda: self.boardButtonClicked(
            self.e4.objectName(), settings.PLAYER))
        self.e5.clicked.connect(lambda: self.boardButtonClicked(
            self.e5.objectName(), settings.PLAYER))
        self.e6.clicked.connect(lambda: self.boardButtonClicked(
            self.e6.objectName(), settings.PLAYER))
        self.e7.clicked.connect(lambda: self.boardButtonClicked(
            self.e7.objectName(), settings.PLAYER))
        self.e8.clicked.connect(lambda: self.boardButtonClicked(
            self.e8.objectName(), settings.PLAYER))

        self.f1.clicked.connect(lambda: self.boardButtonClicked(
            self.f1.objectName(), settings.PLAYER))
        self.f2.clicked.connect(lambda: self.boardButtonClicked(
            self.f2.objectName(), settings.PLAYER))
        self.f3.clicked.connect(lambda: self.boardButtonClicked(
            self.f3.objectName(), settings.PLAYER))
        self.f4.clicked.connect(lambda: self.boardButtonClicked(
            self.f4.objectName(), settings.PLAYER))
        self.f5.clicked.connect(lambda: self.boardButtonClicked(
            self.f5.objectName(), settings.PLAYER))
        self.f6.clicked.connect(lambda: self.boardButtonClicked(
            self.f6.objectName(), settings.PLAYER))
        self.f7.clicked.connect(lambda: self.boardButtonClicked(
            self.f7.objectName(), settings.PLAYER))
        self.f8.clicked.connect(lambda: self.boardButtonClicked(
            self.f8.objectName(), settings.PLAYER))

        self.g1.clicked.connect(lambda: self.boardButtonClicked(
            self.g1.objectName(), settings.PLAYER))
        self.g2.clicked.connect(lambda: self.boardButtonClicked(
            self.g2.objectName(), settings.PLAYER))
        self.g3.clicked.connect(lambda: self.boardButtonClicked(
            self.g3.objectName(), settings.PLAYER))
        self.g4.clicked.connect(lambda: self.boardButtonClicked(
            self.g4.objectName(), settings.PLAYER))
        self.g5.clicked.connect(lambda: self.boardButtonClicked(
            self.g5.objectName(), settings.PLAYER))
        self.g6.clicked.connect(lambda: self.boardButtonClicked(
            self.g6.objectName(), settings.PLAYER))
        self.g7.clicked.connect(lambda: self.boardButtonClicked(
            self.g7.objectName(), settings.PLAYER))
        self.g8.clicked.connect(lambda: self.boardButtonClicked(
            self.g8.objectName(), settings.PLAYER))

        self.h1.clicked.connect(lambda: self.boardButtonClicked(
            self.h1.objectName(), settings.PLAYER))
        self.h2.clicked.connect(lambda: self.boardButtonClicked(
            self.h2.objectName(), settings.PLAYER))
        self.h3.clicked.connect(lambda: self.boardButtonClicked(
            self.h3.objectName(), settings.PLAYER))
        self.h4.clicked.connect(lambda: self.boardButtonClicked(
            self.h4.objectName(), settings.PLAYER))
        self.h5.clicked.connect(lambda: self.boardButtonClicked(
            self.h5.objectName(), settings.PLAYER))
        self.h6.clicked.connect(lambda: self.boardButtonClicked(
            self.h6.objectName(), settings.PLAYER))
        self.h7.clicked.connect(lambda: self.boardButtonClicked(
            self.h7.objectName(), settings.PLAYER))
        self.h8.clicked.connect(lambda: self.boardButtonClicked(
            self.h8.objectName(), settings.PLAYER))
        
        self.d4.setIcon(QtGui.QIcon("../images/icon/white-disk.png"))
        self.e5.setIcon(QtGui.QIcon("../images/icon/white-disk.png"))
        self.d5.setIcon(QtGui.QIcon("../images/icon/black-disk.png"))
        self.e4.setIcon(QtGui.QIcon("../images/icon/black-disk.png"))

    def retranslateUi(self, boardPage):
        _translate = QtCore.QCoreApplication.translate
        boardPage.setWindowTitle(_translate(
            "boardPage", "Othelo (Shiva Radmanesh)"))
        self.label_9.setText(_translate("boardPage", "A"))
        self.label_10.setText(_translate("boardPage", "B"))
        self.label_11.setText(_translate("boardPage", "C"))
        self.label_13.setText(_translate("boardPage", "E"))
        self.label_14.setText(_translate("boardPage", "F"))
        self.label_15.setText(_translate("boardPage", "G"))
        self.label_16.setText(_translate("boardPage", "H"))
        self.label.setText(_translate("boardPage", "1"))
        self.label_2.setText(_translate("boardPage", "2"))
        self.label_3.setText(_translate("boardPage", "3"))
        self.label_4.setText(_translate("boardPage", "4"))
        self.label_5.setText(_translate("boardPage", "5"))
        self.label_6.setText(_translate("boardPage", "6"))
        self.label_7.setText(_translate("boardPage", "7"))
        self.label_8.setText(_translate("boardPage", "8"))
        self.label_12.setText(_translate("boardPage", "D"))
        self.label_17.setText(_translate("boardPage", "White:"))
        self.label_18.setText(_translate("boardPage", "Black:"))
        self.blackScore.setText(_translate("boardPage", "2"))
        self.whiteScore.setText(_translate("boardPage", "2"))
        self.label_21.setText(_translate("boardPage", "Turn: "))
        self.currentMoveLabel.setText(_translate("boardPage", ""))

    def setBoard(self, board, player):
        import boardParser

        def getDisk(val):
            if val == 0:
                return "../images/icon/white-disk.png"
            elif val == 1:
                return "../images/icon/black-disk.png"
            else:
                return ""

        self.getButtonObject(objName='a1').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'a1'))))
        self.getButtonObject(objName='a2').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'a2'))))
        self.getButtonObject(objName='a3').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'a3'))))

        self.getButtonObject(objName='a4').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'a4'))))

        self.getButtonObject(objName='a5').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'a5'))))
        self.getButtonObject(objName='a6').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'a6'))))
        self.getButtonObject(objName='a7').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'a7'))))
        self.getButtonObject(objName='a8').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'a8'))))

        self.getButtonObject(objName='b1').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'b1'))))
        self.getButtonObject(objName='b2').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'b2'))))
        self.getButtonObject(objName='b3').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'b3'))))
        self.getButtonObject(objName='b4').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'b4'))))
        self.getButtonObject(objName='b5').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'b5'))))
        self.getButtonObject(objName='b6').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'b6'))))
        self.getButtonObject(objName='b7').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'b7'))))
        self.getButtonObject(objName='b8').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'b8'))))

        self.getButtonObject(objName='c1').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'c1'))))
        self.getButtonObject(objName='c2').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'c2'))))
        self.getButtonObject(objName='c3').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'c3'))))
        self.getButtonObject(objName='c4').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'c4'))))
        self.getButtonObject(objName='c5').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'c5'))))
        self.getButtonObject(objName='c6').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'c6'))))
        self.getButtonObject(objName='c7').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'c7'))))
        self.getButtonObject(objName='c8').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'c8'))))

        self.getButtonObject(objName='d1').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'd1'))))
        self.getButtonObject(objName='d2').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'd2'))))
        self.getButtonObject(objName='d3').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'd3'))))
        self.getButtonObject(objName='d4').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'd4'))))
        self.getButtonObject(objName='d5').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'd5'))))
        self.getButtonObject(objName='d6').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'd6'))))
        self.getButtonObject(objName='d7').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'd7'))))
        self.getButtonObject(objName='d8').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'd8'))))

        self.getButtonObject(objName='e1').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'e1'))))
        self.getButtonObject(objName='e2').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'e2'))))
        self.getButtonObject(objName='e3').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'e3'))))
        self.getButtonObject(objName='e4').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'e4'))))
        self.getButtonObject(objName='e5').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'e5'))))
        self.getButtonObject(objName='e6').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'e6'))))
        self.getButtonObject(objName='e7').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'e7'))))
        self.getButtonObject(objName='e8').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'e8'))))

        self.getButtonObject(objName='f1').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'f1'))))
        self.getButtonObject(objName='f2').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'f2'))))
        self.getButtonObject(objName='f3').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'f3'))))
        self.getButtonObject(objName='f4').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'f4'))))
        self.getButtonObject(objName='f5').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'f5'))))
        self.getButtonObject(objName='f6').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'f6'))))
        self.getButtonObject(objName='f7').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'f7'))))
        self.getButtonObject(objName='f8').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'f8'))))

        self.getButtonObject(objName='g1').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'g1'))))
        self.getButtonObject(objName='g2').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'g2'))))
        self.getButtonObject(objName='g3').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'g3'))))
        self.getButtonObject(objName='g4').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'g4'))))
        self.getButtonObject(objName='g5').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'g5'))))
        self.getButtonObject(objName='g6').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'g6'))))
        self.getButtonObject(objName='g7').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'g7'))))
        self.getButtonObject(objName='g8').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'g8'))))

        self.getButtonObject(objName='h1').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'h1'))))
        self.getButtonObject(objName='h2').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'h2'))))
        self.getButtonObject(objName='h3').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'h3'))))
        self.getButtonObject(objName='h4').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'h4'))))
        self.getButtonObject(objName='h5').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'h5'))))
        self.getButtonObject(objName='h6').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'h6'))))
        self.getButtonObject(objName='h7').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'h7'))))
        self.getButtonObject(objName='h8').setIcon(QtGui.QIcon(
            getDisk(boardParser.getSquareValue(board, 'h8'))))

        self.currentMoveLabel.setText(settings.PLAYER)

    def boardButtonClicked(self, place, player):
        serialConnector.sender(f"{place} {player}")

    def moveValidated(self, place, player):
        btnObj: QtWidgets.QPushButton
        
        btnObj = self.getButtonObject(objName=place)

        if player == 'W':
            btnObj.setIcon(QtGui.QIcon("../images/icon/white-disk.png"))
        else:
            btnObj.setIcon(QtGui.QIcon("../images/icon/black-disk.png"))

        print("nameeeeeeeeeeeeeeeeeeeeeeeeeeee:   ", str(place))

    
    def setResult(self, winner):
        if winner == "Black" or winner == "White":
            self.validMoveLabel.setText(f"Player {winner} win!")
        else:
            self.validMoveLabel.setText("Tie")

    def getButtonObject(self, objName):
        return self.widget.findChild(QtWidgets.QPushButton, objName)

    def moveInvalid(self, place, player):
        self.validMoveLabel.setText(
            f"{place} is a wrong move for player {player}")
    

    def setScores(self, data: list):
        self.blackScore.setText(str(data.count(1)))
        self.whiteScore.setText(str(data.count(0)))

    